# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a42403533f7c89520ee7dede6edce37691da320ef1af9f80d3515733def24c2c41daf9b03289717c9fa44f85c3c8c66b59bfe6dafe83a81f2b130bb9a3df8051

test:
  secret_key_base: 23018fe472b98e1f8007c65920045e9312371968fb21f6307cb4dcccc0dbdb43e06881f103414588f0e3a064260cce8880fffb075236dc52362545341e7fcb6d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
